### ISSUE TITLE
Python 3.11 support

### ISSUE THREAD

**Issue by klauer** [pcdshub/epicsmacrolib#4]
## Expected Behavior
epicsmacrolib should work on Python 3.11

## Current Behavior
It fails to build with:
```
epicsmacrolib/iocsh.cpp -o build/temp.linux-x86_64-cpython-311/epicsmacrolib/iocsh.o
      epicsmacrolib/iocsh.cpp: In function ‘void __Pyx_AddTraceback(const char*, int, int, const char*)’:
      epicsmacrolib/iocsh.cpp:465:62: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
        465 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
            |                                                              ^~
      epicsmacrolib/iocsh.cpp:5302:5: note: in expansion of macro ‘__Pyx_PyFrame_SetLineNumber’
       5302 |     __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
            |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /opt/hostedtoolcache/Python/3.11.2/x64/include/python3.11/Python.h:42,
                       from epicsmacrolib/iocsh.cpp:25:
      /opt/hostedtoolcache/Python/3.11.2/x64/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```  

## Possible Solution
Re-cythonize the bundled `.cpp` file
