### PR TITLE
DEV/MNT: migrate to GitHub Actions cibuildwheel and pyproject.toml

### LINKED ISSUE #4: Python 3.11 support
## Expected Behavior
epicsmacrolib should work on Python 3.11

## Current Behavior
It fails to build with:
```
epicsmacrolib/iocsh.cpp -o build/temp.linux-x86_64-cpython-311/epicsmacrolib/iocsh.o
      epicsmacrolib/iocsh.cpp: In function ‘void __Pyx_AddTraceback(const char*, int, int, const char*)’:
      epicsmacrolib/iocsh.cpp:465:62: error: invalid use of incomplete type ‘PyFrameObject’ {aka ‘struct _frame’}
        465 |   #define __Pyx_PyFrame_SetLineNumber(frame, lineno)  (frame)->f_lineno = (lineno)
            |                                                              ^~
      epicsmacrolib/iocsh.cpp:5302:5: note: in expansion of macro ‘__Pyx_PyFrame_SetLineNumber’
       5302 |     __Pyx_PyFrame_SetLineNumber(py_frame, py_line);
            |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /opt/hostedtoolcache/Python/3.11.2/x64/include/python3.11/Python.h:42,
                       from epicsmacrolib/iocsh.cpp:25:
      /opt/hostedtoolcache/Python/3.11.2/x64/include/python3.11/pytypedefs.h:22:16: note: forward declaration of ‘PyFrameObject’ {aka ‘struct _frame’}
         22 | typedef struct _frame PyFrameObject;
            |                ^~~~~~
      error: command '/usr/bin/gcc' failed with exit code 1
      [end of output]
```  

## Possible Solution
Re-cythonize the bundled `.cpp` file

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Migrate to GitHub Actions
* Use cibuildwheel instead of our standard CI helpers suite, as we want to create compatible binary wheels for a variety of platforms and a variety of Python versions

## Motivation and Context
Closes #4 

## How Has This Been Tested?
This will be tested on CI

### CODE REVIEW

**Comment by klauer** [comment]
It's all green, guys:
* Python, Windows and MacOS
* 3.9, 3.10, and 3.11
* Wheels for multiple architectures on the matrix of above OS/Python versions
* Test suite for the above OS/Python versions

**Comment by tangkong** [comment]
Whoa this is crazy.  I thought I'd never see full green again

**Review by tangkong — APPROVED** [review]
Seems good, tests pass.  A new set of tests but they all seem to pass so I'm happy

**Review by ZLLentz — APPROVED** [review]
LGTM
